export const CONFIG = {
    COLIMA_VERSION: process.env.REACT_APP_COLIMA_VERSION,
    DOCKER_BUILDX_VERSION: process.env.REACT_APP_DOCKER_BUILDX_VERSION,
    DOCKER_COMPOSE_VERSION: process.env.REACT_APP_DOCKER_COMPOSE_VERSION,
}

export default CONFIG